### PR TITLE
Ignore src/dst port 443

### PR DESCRIPTION
**Pull request by karashiiro**
Avoids unnecessary zlib decompression errors.

### CODE REVIEW

**Comment by karashiiro** [comment]
Unless of course HTTPS packets are used for something we need, but I’m fairly certain they aren’t.

**Comment by karashiiro** [comment]
Actually, checking the magic already prevents this from causing issues, might still be a small optimization though. Feel free to merge it or not if you want.

**Comment by karashiiro** [comment]
Closing actually, this may cause unintended side-effects.

**Comment by ayyaruq** [comment]
Late to the party but I don't think there'd be any unintended side effects. The magic check is actually a bit iffy since it means you can't parse chat, but I hesitate as to why someone would need to parse chat for any non-dodgy reason.

**Pull request closed without merging**
